version: '3'
services:
  db:
    image: 'postgres:11.5-alpine'
    networks:
      - webnet
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - webnet
    ports:
      - '6379:6379'
networks:
  webnet:
volumes:
  dbdata:
